In [1]:
from sklearn.linear_model import LogisticRegression
import numpy as np
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split, cross_val_score, KFold

In [2]:
iris = load_iris()

In [3]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [ ]:
cross_val_score(LogisticRegression(), iris.data, iris.target, cv=3)

c:\Users\21raj\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.98, 0.96, 0.98])

In [5]:
cross_val_score(SVC(), iris.data, iris.target, cv=3)

array([0.96, 0.98, 0.94])

In [6]:
cross_val_score(RandomForestClassifier(), iris.data, iris.target, cv=3)

array([0.98, 0.94, 0.96])

In [9]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train, y_train)
    return model.score(x_test, y_test)

In [21]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)
scores_lr=[]
scores_svm=[]
scores_rf=[]

for train_index,test_index in folds.split(iris.data, iris.target):
    #print(train_index, test_index)
    X_train, X_test = iris.data[train_index], iris.data[test_index]
    y_train, y_test = iris.target[train_index], iris.target[test_index]
    scores_lr.append(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=250), X_train, X_test, y_train, y_test))

c:\Users\21raj\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [22]:
scores_rf

[0.98, 0.94, 0.98]

In [23]:
scores_lr

[0.98, 0.96, 0.98]

In [24]:
scores_svm

[0.96, 0.98, 0.94]

In [14]:
def avg(scores):
    return np.mean(scores)

In [25]:
avg(scores_rf)

0.9666666666666667

In [26]:
avg(scores_lr)

0.9733333333333333

In [27]:
avg(scores_svm)

0.96